# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: ubuntu:latest

    working_directory: ~/repo

    steps:
      - run: apt-get update
      - run: apt-get install -y openjdk-8-jdk maven docker

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # run tests!
      - run: mvn verify

      - store_test_results:
          path: ./target/surefire-reports

      - store_artifacts:
          path: /tmp/artifacts
          destination: artifacts

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # build container
      - run: mvn verify -Pbuild-container
